# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0002_auto_20170526_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
