# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0005_auto_20170601_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
