# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0006_auto_20170601_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
