# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0007_auto_20170601_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
