# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0010_auto_20170605_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_question_text', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='programming_question',
            field=models.ManyToManyField(to='kibosurvey.ProgrammingQuestion'),
        ),
    ]
