# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0013_results_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='update_date',
            field=models.DateTimeField(blank=True, default=False),
        ),
    ]
