# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0014_auto_20170607_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
