# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0015_auto_20170607_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='results',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
