# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kibosurvey', '0016_auto_20170607_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='programmingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_number', models.IntegerField(default=0)),
                ('question_number', models.IntegerField(default=0)),
                ('rating_number', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='productResults',
        ),
    ]
